//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class CTDV
    {
        public string maDV { get; set; }
        public string maCTHD { get; set; }
        public Nullable<int> soLuong { get; set; }
        public Nullable<decimal> tongGia { get; set; }
    
        public virtual CTHD CTHD { get; set; }
        public virtual DICHVU DICHVU { get; set; }
    }
}
