//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class CTHD
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CTHD()
        {
            this.CTDVs = new HashSet<CTDV>();
        }
    
        public string maCTHD { get; set; }
        public Nullable<System.DateTime> ngayThue { get; set; }
        public Nullable<System.DateTime> ngayHetHan { get; set; }
        public string maHD { get; set; }
        public string maPhong { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTDV> CTDVs { get; set; }
        public virtual HOPDONG HOPDONG { get; set; }
        public virtual PHONG PHONG { get; set; }
    }
}
