//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class DIENNUOC
    {
        public string maPhong { get; set; }
        public System.DateTime thoiGian { get; set; }
        public Nullable<int> CSDCu { get; set; }
        public Nullable<int> CSDMoi { get; set; }
        public Nullable<int> CSNCu { get; set; }
        public Nullable<int> CSNMoi { get; set; }
    
        public virtual PHONG PHONG { get; set; }
    }
}
