//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHIEUTHANHTOAN
    {
        public string maPhieu { get; set; }
        public Nullable<decimal> tongTien { get; set; }
        public Nullable<System.DateTime> ngayLapPhieu { get; set; }
        public Nullable<System.DateTime> ngayThanhToan { get; set; }
        public string maPhong { get; set; }
    
        public virtual PHONG PHONG { get; set; }
    }
}
